globals = {
    "turtle",
    "fs",
    "rednet",
    "peripheral",
    "term",
    "textutils",
    "colors",
    "disk",
    "gps",
    "http",
    "io",
    "keys",
    "paintutils",
    "parallel",
    "vector",
    "window",
    "assert_true",
    "assert_false",
    "assert_eq",
    "assert_ne",
    "assert_float_eq",
    "assert_float_ne",
    "expect_true",
    "expect_false",
    "expect_eq",
    "expect_ne",
    "expect_float_eq",
    "expect_float_ne",
    "store_check_fail",
    "expect_gt",
    "expect_ge",
    "expect_lt",
    "expect_le",
    "assert_gt",
    "assert_ge",
    "assert_lt",
    "assert_le",
    "patch",
    "patch_local",
    "reset_patches",
    "MagicMock"
}
ignore = {
    "111",
    "131",
}
unused = false
max_line_length = false
allow_defined = true
exclude_files = {
    ".luarocks",
    "install",
    "stub",
    "logs",
}
