globals = {
    -- cc globals
    "colors",
    "colours",
    "commands",
    "disk",
    "fs",
    "gps",
    "help",
    "http",
    "io",
    "keys",
    "os",
    "paintutils",
    "parallel",
    "peripheral",
    "pocket",
    "printError",
    "rednet",
    "redstone",
    "rs",
    "settings",
    "shell",
    "term",
    "textutils",
    "turtle",
    "vector",
    "window",
    "write",
    -- Test Harness
    "assert_true",
    "assert_false",
    "assert_eq",
    "assert_ne",
    "assert_float_eq",
    "assert_float_ne",
    "expect_true",
    "expect_false",
    "expect_eq",
    "expect_ne",
    "expect_float_eq",
    "expect_float_ne",
    "expect_arr_eq",
    "store_check_fail",
    "expect_gt",
    "expect_ge",
    "expect_lt",
    "expect_le",
    "assert_gt",
    "assert_ge",
    "assert_lt",
    "assert_le",
    "patch",
    "patch_local",
    "reset_patches",
    "Mock",
    "sleep",
}
ignore = {
    -- "111", -- setting undefined global
    "131", -- unused globals
}
unused = false
max_line_length = false
allow_defined = true
exclude_files = {
    ".luarocks",
    "install",
    -- "stub",
    "logs",
    "rom.2",
}
