name: ci

on:
  push:
    # branches:
    #   - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.2"

      - uses: leafo/gh-actions-luarocks@v4

      - name: build
        run: |
          luarocks install luacheck

      - name: Lint (luacheck)
        run: |
          luacheck cc-libs

      - name: Lint (stylua)
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v4
          args: --check .

      - name: Run Tests
        run: |
          cd tests && lua runtests.lua
