name: ci

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint_test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.2"

      - name: Setup luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Lint (luacheck)
        run: luacheck .

      - name: Lint (stylua)
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

      - name: Run Tests
        run: cd tests && lua runtests.lua

  increment_version:
    name: Increment Version
    uses: automas-dev/reusable-workflows/.github/workflows/increment_version.yml@v1.1
    secrets: inherit
    with:
      dry-run: ${{ github.ref != 'refs/heads/main' }}
      aliases: true

    needs: [lint_test]

    permissions:
      contents: write

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'NO RELEASE')

    needs: [lint_test, increment_version]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Write version number to file
        env:
          VERSION: ${{ needs.increment_version.outputs.version }}
        run: |
          echo $VERSION > cc-libs/.version
          echo $VERSION > cc-apps/.version

      - name: Archive library
        uses: actions/upload-artifact@v4
        with:
          name: cc-libs
          path: cc-libs

      - name: Archive apps
        uses: actions/upload-artifact@v4
        with:
          name: cc-apps
          path: cc-apps

      - name: Create Library Archive
        run: tar -cf cc-libs.tar cc-libs

      - name: Create Apps Archive
        run: tar -cf cc-apps.tar cc-apps

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: cc-libs.tar,cc-apps.tar
          makeLatest: true
          generateReleaseNotes: true
          tag: ${{ needs.increment_version.outputs.tag }}

  check:
    runs-on: ubuntu-latest
    if: always()

    needs: [lint_test, increment_version]

    timeout-minutes: 1

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
