name: Release

on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Archive library
        uses: actions/upload-artifact@v4
        with:
          name: cc-libs
          path: |
            cc-libs

      - name: Archive apps
        uses: actions/upload-artifact@v4
        with:
          name: cc-apps
          path: |
            cc-apps

      - name: Create Library Archive
        run: |
          tar -cf cc-libs.tar cc-libs

      - name: Create Apps Archive
        run: |
          tar -cf cc-apps.tar cc-apps

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: cc-libs.tar,cc-apps.tar
          makeLatest: true
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
