name: test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.2"

      - uses: leafo/gh-actions-luarocks@v4

      - name: build
        run: |
          luarocks install luacheck

      - name: Lint
        run: |
          luacheck cc-libs

      - name: Run Tests
        run: |
          cd tests && lua runtests.lua
